### ISSUE TITLE
CHECK_CONN_FREQ not working ?

### ISSUE THREAD

**Issue by twobeass** [SamEureka/balenaPhono#14]
First of all, GREAT PROJECT!!
It is running on a Pi Zero 2W with a Behringer UCA202 to feed the Audio from my Turntables to my Sonos System! It is working like charm exept for just one little thing!
The CHECK_CONN_FREQ Variable seems to be ignored:
![image](https://github.com/SamEureka/balenaPhono/assets/4639195/846611c1-f77f-4ef5-b44e-2899a694fa85)
The log tells me this all the time:
![image](https://github.com/SamEureka/balenaPhono/assets/4639195/9319292a-5ae0-4bd6-880a-71a7a8a1e122)

Or am i doing something wrong ?
Thanks for your support!

**Comment by SamEureka** [comment]
@twobeass 

I'm so glad the project is working for you!

The only variable that I set besides CHECK_CONN_FREQ is REBOOT_TIME. It is set to the default in this screenshot and that will reboot the whole system at 4am. 

![gnome-shell-screenshot-6s0vvs](https://github.com/SamEureka/balenaPhono/assets/4239748/cabfecf3-7c64-4708-9e22-f85bd317677f) 

The most recent version of balenaPhono should work just fine without setting anything at all. You can change the password variables if you are worried about such things. But it isn't required. 

Put in another issue if you have any problems or suggestions.

Very respectfully,
//Sam
